name: Sync configurations

on:
  push:
    branches:
      - main

jobs:
  sync-triage-config:
    if: github.repository == 'jefftriplett/.github'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - jefftriplett/django-jobs
          - jefftriplett/toggl-standup
    steps:
      - name: Clone main repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Clone secondary repository
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }}
          path: vendor/${{ matrix.repo }}
          persist-credentials: false

      - name: Detect changes
        id: detect_changes
        run: |
          echo '${{ matrix.repo }}'
          ls '${{ matrix.repo }}'

          echo 'vendor/${{ matrix.repo }}'
          ls 'vendor/${{ matrix.repo }}'
